### ISSUE TITLE
Loopback with carthage

### ISSUE THREAD

**Issue by xnramx** [strongloop/loopback-sdk-ios#111]
I've tried to install the Loopback framework with Carthage but it didn't work.

Result: "The operation couldn’t be completed. (LaunchServicesError error 0.)"

![Error print screen](http://i.stack.imgur.com/NQOda.png)
Do you know how to fix it?

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.

As for your question, I've never used Carthage, so I wouldn't know. Have you used that framework before @bajtos?

**Comment by bajtos** [comment]
Nope, I am not familiar with Carthage either :(

**Comment by superkhau** [comment]
@xnramx I'm going to close this issue as we're probably not going to prioritize it anytime soon. I suggest getting help from community at https://gitter.im/strongloop/loopback, maybe someone who is a Carthage expert will be able to guide you in the right direction.

Maybe try posting at the Carthage repo and see if they can give you more insight. Feel free to ping in this issue if you find anything we can actually fix (or submit a PR) and I would be glad to help you out again. I also will reopen this issue at that time instead.
