### ISSUE TITLE
iOS API documentation isnt working

### ISSUE THREAD

**Issue by imarkopolo** [strongloop/loopback-sdk-ios#118]
So i'm trying to get your iOS API Documentation - http://apidocs.strongloop.com/loopback-sdk-ios/api/annotated.html
and its an html error "Cannot GET /loopback-sdk-ios/api/annotated.html"
can someone give me a working link for it?

**Comment by ArtIstomin** [comment]
+

**Comment by riterrani** [comment]
+

**Comment by crandmck** [comment]
This was due to https://github.com/strongloop/loopback-sdk-ios/pull/91.

**Comment by crandmck** [comment]
closed in favor of https://github.com/strongloop/loopback-sdk-ios/issues/103.
