### ISSUE TITLE
How do I put a custom field into the header requests rather than just accessToken? 

### ISSUE THREAD

**Issue by dongmai** [strongloop/loopback-sdk-ios#119]

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs or try asking on our [Gitter](https://gitter.im/strongloop/loopback). See https://github.com/strongloop/loopback/wiki/Questions for more details.
Please post questions at on our [Google Groups forum](https://groups.google.com/forum/#!forum/loopbackjs) or try asking using live chat on our [Gitter](https://gitter.im/strongloop/loopback). We reserve GitHub issues for features and bug reports only. See https://github.com/strongloop/loopback/wiki/Questions for more details.
