### ISSUE TITLE
Duplicated extern string "AFQueryStringFromParametersWithEncoding" and "AFContentTypesFromHTTPHeader" with AFNetworking

### ISSUE THREAD

**Issue by trunglee** [strongloop/loopback-sdk-ios#22]
Why we don't rename the prefix from AF to SLAF for these constants too?, if the project uses both loopback and AFNetworking, it can not build.

**Comment by hideya** [comment]
I want this fixed too

**Comment by hideya** [comment]
I've made a pull request https://github.com/strongloop/loopback-sdk-ios/pull/36 for the proposed fix.
Thanks, @trunglee, for pointing out the issue!

**Comment by bajtos** [comment]
I am closing the issue then. @raymondfeng could you please make a new release of the SDK?
