### ISSUE TITLE
Logout user is not working - GET instead of POST used

### ISSUE THREAD

**Issue by benmarten** [strongloop/loopback-sdk-ios#26]
The logout method in the LB iOS FW uses GET instead of POST. Hence the logout is not working (404).

It should be - LBUser.m:

		- (SLRESTContract*)contract
		{
		    SLRESTContract* contract = [super contract];

		    [contract addItem:[SLRESTContractItem itemWithPattern:[NSString stringWithFormat:@"/%@/logout", self.className] verb:@"POST"]
		            forMethod:[NSString stringWithFormat:@"%@.logout", self.className]];

		    return contract;
		}

**Comment by hideya** [comment]
You are right.  It should be POST.
However, in my simple test environment, the logout method seems working w/o fixing the verb...
My simple test does; login, logout then logout again.  The 2nd logout fails with Status 500 "could not find accessToken" as expected for both cases w/ and w/o the verb fix.  

@benmarten, I'm trying to reproduce the issue you encountered and thinking to propose to add a test for the error.  Could you tell me what I could be missing?

**Comment by benmarten** [comment]
Sure, don't have a lot of time atm, but if you can share a sample project, then i am happy to take a look?
Or what test is failing?

**Comment by hideya** [comment]
Thanks!  I just modified the unit test `LBUserTests.m` and ran the server found in `LoopBackTests/server`.  The test succeeds (i.e. the 2nd logout fails as expected) regardless of the verb fix.
```
- (void)testLogout {
    ASYNC_TEST_START
    [self.repository userByLoginWithEmail:@"testUser@test.com" password:@"test" success:^(LBUser* user) {
        [self.repository logoutWithSuccess:^(void) {
            // The following second try to logout should fail if the first logout succeeded
            [self.repository logoutWithSuccess:ASYNC_TEST_FAILURE_BLOCK
            failure:^(NSError *error) {
                ASYNC_TEST_SIGNAL
            }];
        } failure:ASYNC_TEST_FAILURE_BLOCK];
    } failure:ASYNC_TEST_FAILURE_BLOCK];
    ASYNC_TEST_END
}
```

**Comment by benmarten** [comment]
I just tested it again in my latest app. It definitely fails for me with GET, with POST it works...
I can't get the tests you mentioned running, ran pod install, but there are still errors.... how do i actually run the tests in xcode?

**Comment by hideya** [comment]
Thanks for sparing time on this!  To run the test, first the test server needs to be started:
```
cd loopback-sdk-ios/LoopBackTests/server
npm install
node index.js
```
Then tests under LoopBackTests can be run from xcode's navigation pane.  Am I answering your question?

**Comment by benmarten** [comment]
Please update package.json to latest packages: 

ran it with: `npm-check-updates -u`

"dependencies": {
    "loopback": "2.x.x",
    "loopback-component-push": "~1.4.4",
    "loopback-component-storage": "~1.3.1",
    "loopback-datasource-juggler": "^2.21.0",
    "morgan": "^1.5.2"
  }

Then logout fails...

**Comment by hideya** [comment]
Thank you so much for pointing it out!  Now I'm able to reproduce the issue!

**Comment by hideya** [comment]
Checking LBUser implementation, I found another issue.  I've fixed them and made a pull request https://github.com/strongloop/loopback-sdk-ios/pull/35  Thank you, @benmarten, for your help!

**Comment by hideya** [comment]
@bajtos, would you mind to close this as fixed?  
@benmarten, the pull request https://github.com/strongloop/loopback-sdk-ios/pull/35 has been merged. Thanks again for your help :-)
