### ISSUE TITLE
LBFile/LBContainer API improvements?

### ISSUE THREAD

**Issue by hideya** [strongloop/loopback-sdk-ios#34]
LBFile looks left in a halfway-done status, and I'm wondering any effort should be made to update it 
so that it looks closer to the Android one.  Currently, the APIs for iOS's and Android's SDKs LB file support look very different (and Android one seems more matured).  Considering easiness of multi-device support by developers, I think the both are better be aligned.

LBFile doesn't use LBContainer at all, whereas LBContainer class exists in the SDK.  LBContainer doesn't have any methods for LBFile operation neither.

Furthermore, LBFile's API philosophy looks different from Android one.  LBFile seems designed more like a representation of a local file which can be stored onto the server.  Android's File looks more like a representation of a remote file that can be downloaded to local.

If we make iOS SDK's file API close to Android one, it will break compatibility.  As far as I can tell, the following breaking changes will be needed:

- Use of LBContainer instead of NSString in LBFile when specifying a container.
- Removal of [LBFile -uploadWithSuccess:failure:] method.
- Removal of LBFile.localPath property.

Even with those backward incompatible changes, I think it is beneficial to make the above mentioned updates to LBFile/LBContainer.

Does anyone have any thoughts on this?

**Comment by aaresta** [comment]
Is there any example code of how to use LBFile and LBContainer?

**Comment by hideya** [comment]
The text cases for LBFile and LBContainer might be helpful to understand the usage:
https://github.com/hideya/loopback-sdk-ios/blob/master/LoopBackTests/LBFileTests.m
https://github.com/hideya/loopback-sdk-ios/blob/master/LoopBackTests/LBContainerTests.m

**Comment by hideya** [comment]
Since I've just submitted a compatibility breaking PR https://github.com/strongloop/loopback-sdk-ios/pull/43 (with support from @bajtos), I'm thinking to make this breaking change right next.  As described above, the current LBFile and LBContainer seemingly left in a halfway-done status.  I'll fix them and make the API looks more close to Android's.

**Comment by hideya** [comment]
Hmm... I'm in middle of updating LBFile/LBContainer API and realized the usage becomes far more involved than I initially thought compared to the current simple and easy API (although it is far less powerful).  I may propose to add some simple wrapper to sugarcoat the complexity, or stay with the current simple and easy design, make minimum fix and add missing features like binary/stream upload/download.

For example, in the updated version (which follows Android's API approach), we need the following three steps to download a file on the server:

1) get a container object by specifying a container name
2) get a file object by specifying the container object and a file name
3) download the file by specifying a local path

And all the three operations are done asynchronously, a nest nightmare happens.
The following is a working test code after the API update:
```
LBRESTAdapter *adapter = [LBRESTAdapter adapterWithURL:[NSURL URLWithString:@"http://..."]];
    LBFileRepository *repository = (LBFileRepository*)[adapter repositoryWithClass:[LBFileRepository class]];

    LBRESTAdapter *adapterForContainer = [LBRESTAdapter adapterWithURL:[NSURL URLWithString:@"http://..."]];
    LBContainerRepository *containerRepo = (LBContainerRepository*)[adapterForContainer repositoryWithClass:[LBContainerRepository class]];

    [containerRepo getContainerWithName:@"container1" success:^(LBContainer *container) {
        repository.container = container;

        [repository getFileWithName:@"f1.txt" success:^(LBFile *file) {
            [file downloadWithFilePath:fullPath success:^(void) {
                // do something with the downloaded file
            } failure:^(NSError *error) {
                // error handling
            }
        } failure:^(NSError *error) {
            // error handling
        }
    } failure:^(NSError *error) {
        // error handling
    }
```

The previous API allowed something simple like the following:
```
    LBRESTAdapter *adapter = [LBRESTAdapter adapterWithURL:[NSURL URLWithString:@"http://..."]];
    LBFileRepository *repository = (LBFileRepository*)[adapter repositoryWithClass:[LBFileRepository class]];

    [repository getFileWithName:@"f1.txt" container:@"container1" localPath:localDir success:^(LBFile *file) {
        // do something with the downloaded file
    } failure:^(NSError *error) {
        // error handling
    }
```

**Comment by bajtos** [comment]
>  I may propose to add some simple wrapper to sugarcoat the complexity, or stay with the current simple and easy approach, make minimum fix and add missing features like binary/stream upload/download.

Both ways are fine with me. Let's pick the one that requires less work to get implemented.

**Comment by hideya** [comment]
@bajtos Thanks for your feedback!   I made a PR #47 that keeps current API and adds missing features as a convenience methods to LBFileRepository.  How does the PR look to you?

**Comment by hideya** [comment]
@bajtos would you please close this as PR #47 has been merged?

**Comment by hideya** [comment]
I'm closing this as PR #47 has been merged
