### ISSUE TITLE
LB 2.0 PersistedModel support

### ISSUE THREAD

**Issue by hideya** [strongloop/loopback-sdk-ios#40]
LoopBack 2.0 introduced "New object PersistedModel" ([Release Notes](http://docs.strongloop.com/display/public/LB/LoopBack+2.0+release+notes)) but iOS SDK has not yet updated to follow the new convention. Although it breaks backward code compatibility, thought it would better be done.

**Comment by hideya** [comment]
I talked with @bajtos about this.  Here is a plan we discussed.  It would be really great if I could hear any feedback...

Currently, all the LB model classes inherit `LBModel`, and `LBModel` supports CRUD operation.

[current]
```
LBModel --> LBUser, LBAccessToken, LBInstallation, LBFile, LBContainer
```
The plan is to introduce `LBPersistedModel` and make the class hierarchy looks like the below (consisted with the server side):

[plan]
```
LBModel -+-> LBPersistedModel --> LBUser, LBAccessToken, LBInstallation
         |
         +-> LBFile, LBContainer
```

Also all the CRUD methods found in `LBModel` and `LBModelRepository` (those with leading * below -- just a few supported at this moment) will be moved to `LBPersistedModel` and `LBPersistedModelRepository` respectively:

```
LBModel
- (id)objectForKeyedSubscript:(id <NSCopying>)key;
- (void)setObject:(id)obj forKeyedSubscript:(id <NSCopying>)key;
- (NSDictionary *)toDictionary;
*- (void)saveWithSuccess:(LBModelSaveSuccessBlock)success failure:(SLFailureBlock)failure;
*- (void)destroyWithSuccess:(LBModelDestroySuccessBlock)success failure:(SLFailureBlock)failure;

LBModelRepository
- (SLRESTContract *)contract;
- (LBModel *)modelWithDictionary:(NSDictionary *)dictionary;
*- (void)findById:(id)_id success:(LBModelFindSuccessBlock)success failure:(SLFailureBlock)failure;
*- (void)allWithSuccess:(LBModelAllSuccessBlock)success failure:(SLFailureBlock)failure;
```

Does this sound reasonable...?

**Comment by bajtos** [comment]
> Does this sound reasonable...?

Sounds good to me! :+1: 

>  A question about "id" of model.  To which does it belong; Model or PersistedModel?
I thought that the ID is used to identify a saved object via crud operation, but models.js
includes 'id', so I got a bit confused...

IMO, `id` belongs to `PersistedModel`. It is possible for a `Model` to have an id property too, but it's not always the case.

/cc @raymondfeng

**Comment by hideya** [comment]
Thanks @bajtos for getting back to me with answers!
On the iOS SDK side, currently `id` is immutable in both `Model` and `PersistedModel`.  Maybe it is should be made mutable in `Model` in that case.

**Comment by bajtos** [comment]
I would personally remove `Model.id` completely and keep `PersistedModel.id` only. Take for example LBFile and LBContainer classes, I believe they don't have any id, do they?

**Comment by hideya** [comment]
No, they don't.  Actually I meant the same -- making it mutable -> move the special treatment to make `id` immutable to `PersistedModel` -> no special code for `id` in `Model` (sorry for the unclearness in my previous post).  Thanks for the feedback!

**Comment by hideya** [comment]
The change (PR #43) has been merged.
Please feel free to close this issue.
