### ISSUE TITLE
Issue while uploading LBFile.h

### ISSUE THREAD

**Issue by lennartstolz** [strongloop/loopback-sdk-ios#45]
```objectivec
- (void)uploadWithSuccess:(LBFileUploadSuccessBlock)success failure:(SLFailureBlock)failure; 
```
This Function uses **/../ModelName/prototype** instead of the .**./ModelName/{containerName}** for uploading the file. I'm not sure if this is a bug, or I am just stupid.

**Comment by hideya** [comment]
Could you explain me a bit more about the issue?  I'm not quite sure what those paths are.  Sorry for my lack of understanding...

**Comment by lennartstolz** [comment]
Hey hideya,

**Comment by lennartstolz** [comment]
Hey @hideya,

thanks for you reply and no worries about the lack of understanding. I know this three lines of issue were not enough to get an idea of what I'm talking about. :wink: 

So I added a short code snippet to show you how I create a new LBFile-Object.

```objectivec
LBFileRepository *receiptFiles = [LBFileRepository repositoryWithClassName:@"Receipt"];
[receiptFiles setAdapter:self.loopbackAdapter];
NSString *imagePath = [[NSBundle mainBundle] pathForResource:@"2015-06-01-aldi" ofType:@"png"];
LBFile *file = [receiptFiles createFileWithName:@"2015-06-01-aldi.png" localPath:imagePath container:@"demo-receipts-us"];
```

This works like charm. 
When I try to upload the file with the following method:

```objectivec
[file uploadWithSuccess:^{
 NSLog(@"Juhu!");
} failure:^(NSError *error) {
 NSLog(@"%@", error.localizedDescription);
}];
```

The path property of the SLRESTAdapter.m in the method:

```objectivec
- (void)requestWithPath:(NSString *)path
                   verb:(NSString *)verb
             parameters:(NSDictionary *)parameters
              multipart:(BOOL)multipart
           outputStream:(NSOutputStream *)outputStream
                success:(SLSuccessBlock)success
                failure:(SLFailureBlock)failure {
// Loopback code in here ... 
}
```

is the following: **Receipt/prototype/upload**.

But for using the normal Loopback Route for POST to the API it should be: **Receipt/demo-receipts-us/upload**

I hope it's now a bit more understandable.

Best Lennart

**Comment by hideya** [comment]
Hi @lennartstolz,
Thanks for the detailed explanation!  Checking the code, I noticed `@"Receipt"` is given when creating the `LBFileRepository`.  Is it a class you defined?  As far as I know, usual way to create a file object is something like the following:
```Objective-C
LBFileRepository *repository = (LBFileRepository*)[adapter repositoryWithClass:[LBFileRepository class]];
LBFile *file = [repository createFileWithName:fileName localPath:pathToLocalDir container:containerName];
```
Could you try this and see if it works for you?

**Comment by lennartstolz** [comment]
Thanks for your reply @hideya ,

I'll have a detailed look on this in a bit. Just tried it for a few minutes and it looks good (no errors anymore and success-block called, but the image isn't in the AWS S3 bucket. 

I think I have to create a **Receipt** class first, because using **LBFileRepository** is not working with the Loopback Route **/Receipt/container/upload**.

**Comment by hideya** [comment]
You are very welcome, @lennartstolz 
As far as I know, LoopBack's storage service's URI's format is fixed like `/api/containers/:container/upload`  Have you checked out the following document?
http://docs.strongloop.com/display/public/LB/Storage+component

**Comment by lennartstolz** [comment]
:+1: @hideya. Thanks for this link. 
I thought it would be possible to use StorageComponent as persistent storage for an model.

But this solution makes more sense.
