### ISSUE TITLE
Import of MobileCoreServices.h missing @ LBFile.m

### ISSUE THREAD

**Issue by lennartstolz** [strongloop/loopback-sdk-ios#46]
Hey there, if you use the loopback-sdk-ios with cocoa pods, there are three issues at <b>LBFile.m</b> because the following import is missing.

```objectivec
#import <MobileCoreServices/MobileCoreServices.h>
```

In the Loopback.xcodeproj this import is inside the <b>LoopBack-Prefix.pch</b>-file, but this one is ignored by cocoa pods.

Best Lennart

**Comment by hideya** [comment]
Thanks for pointing it out, @lennartstolz .  I'll work on fixing it!

**Comment by hideya** [comment]
@lennartstolz  actually, I guess it is a cocoa pods configuration issue.  Would you try the following?
http://stackoverflow.com/questions/21577655/how-can-i-include-a-pch-for-a-specific-pod-in-cocoapods

**Comment by lennartstolz** [comment]
Hey @hideya,

thanks for your reply.

As mentioned inside the  [Podspec Syntax Reference](http://guides.cocoapods.org/syntax/podspec.html#prefix_header_file) using this attribute is not recommended. 

> This attribute is not recommended as Pods should not pollute the prefix header of other libraries or of the user project.

Or did I misunderstood the article @ stackoverflow?

Best Lennart

**Comment by hideya** [comment]
Hey @lennartstolz,

Oops, I missed that part... sorry...
So, I got the same question...

> Are we supposed to develop libraries without anything in the .pch?

Do you know the answer?

**Comment by hideya** [comment]
I guess it is harmless to put the import to **LBFile.m**.  Would you please try putting the following and see if it works?
```Objective-C
#if TARGET_OS_IPHONE
#import <MobileCoreServices/MobileCoreServices.h>
#endif
```
In order to make the OS X build also work, we need #if there.  If it works, would you mind to submit a pull request for the change?

**Comment by hideya** [comment]
@lennartstolz, thank you so much for filing the PR!

**Comment by hideya** [comment]
@lennartstolz if you don't have time to work on changes to reflect my comments on your PR https://github.com/strongloop/loopback-sdk-ios/pull/50 , I'd be happy to take it over and try to get integrated into the codebase.  Please let me know if you'd like me to do so.

**Comment by lennartstolz** [comment]
@hideya Sorry for not answering at #50. At the earliest I would start integrating your changes in the upcoming week. So I would be really happy if you take it over. Best Lennart!

**Comment by lennartstolz** [comment]
Ok! Forget my last comment @hideya. I've created a new request: #53

**Comment by hideya** [comment]
:-) Thank you, @lennartstolz !  Hope I didn't pressure you to do it quicker...  Much appreciated!
