### ISSUE TITLE
AFNetworking EXC_BAD_ACCESS while using downloadAsDataWithName[...] in LBFile.m (iOS Device only)

### ISSUE THREAD

**Issue by lennartstolz** [strongloop/loopback-sdk-ios#54]
Hey @ all, 

I ran into the following issue:
```console
AFNetworking (15): EXC_BAD_ACCESS (code=1, address=0x6647000)
```
in Line 797 in [SLAFURLConnectionOperation.m](https://github.com/strongloop/loopback-sdk-ios/blob/master/SLAFNetworking/SLAFURLConnectionOperation.m/#L797 "SLAFURLConnectionOperation.m").

I used this methof of *LBFile.h*:
```objectivec
- (void)downloadAsDataWithName:(NSString *)name
                     container:(NSString *)container
                       success:(LBFileDownloadAsDataSuccessBlock)success
                       failure:(SLFailureBlock)failure;
```

In the simulator it works like charm. On real iOS devices it crashes. :fire: 

Best Lennart

--- 

#### EDIT (2015-08-13)

I use this method to download a image from amazon s3.

**Comment by hideya** [comment]
@lennartstolz , thank you for reporting the issue.  I'm traveling right now and will get back to you as soon as I get home.  Sorry for any inconvenience...

**Comment by hideya** [comment]
@lennartstolz, I found an issue in the implementation of `downloadAsDataWithName:container:success:failure:` and fixed it.
The updated PR https://github.com/strongloop/loopback-sdk-ios/pull/47 includes the fix.  Would it be possible for you to try it out and see if the crash in your environment is fixed?

FYI, the issue was missing `__block` keyword at the top of the following line:
https://github.com/hideya/loopback-sdk-ios/blob/fix/lbfile/LoopBack/LBFile.m#L231

**Comment by lennartstolz** [comment]
Hey @hideya. Thanks for your reply. I've added your quickfix to my project. And it still fails on my iPhone 6 testing device.

**Comment by hideya** [comment]
Thanks, @lennartstolz, for quickly checking it.  Hmm... OK, I'll dig the issue deeper.  Please give me a bit more time...

**Comment by lennartstolz** [comment]
Sure! Sounds great. As far as I can see the issue appears after the success()-block is called. 

in Line 186 in [SLAFURLConnectionOperation.m](https://github.com/strongloop/loopback-sdk-ios/blob/master/SLAFNetworking/SLRESTAdapter.m/#L186 "SLRESTAdapter.m") the responseData seems valid.

Perhaps I've found the problem (It's working now on all of my testing devices :smile: ) but I'm not sure if this is just a side effect or the bugfix.

Inside 

```objectivec
- (void)downloadWithName:(NSString *)name { ... } 
```

the success()-Block was called with no value inside. 

After adding value like in the following, it works:

```objectivec
- (void)downloadWithName:(NSString *)name
               container:(NSString *)container
            outputStream:(NSOutputStream *)outputStream
                 success:(LBFileDownloadSuccessBlock)success
                 failure:(SLFailureBlock)failure {

    [self invokeStaticMethod:@"download"
                  parameters:@{ @"name": name,
                                @"container": container }
                outputStream:outputStream
                     success:^(id value) {
                         success(value);
                     }
                     failure:failure];
}
```

**Comment by hideya** [comment]
Ahhh!  I see the issue!  Thank you, @lennartstolz, for the additional info.

Instead of changing `downloadWithName:container:outputStream:success:failure:`, could you try the following changes in `downloadAsDataWithName:container:success:failure:`? (removal of `id value` from Line 236):

```objc
- (void)downloadAsDataWithName:(NSString *)name
                     container:(NSString *)container
                       success:(LBFileDownloadAsDataSuccessBlock)success
                       failure:(SLFailureBlock)failure {

    __block NSOutputStream *outputStream = [[NSOutputStream alloc] initToMemory];

    [self downloadWithName:name
                 container:container
              outputStream:outputStream
                   success:^() { // <- remove `id value` from the argument
                       NSData *data =
                        [outputStream propertyForKey:NSStreamDataWrittenToMemoryStreamKey];
                       success(data);
                   }
                   failure:^(NSError *err) {
                       [outputStream close];
                       failure(err);
                   }];

}
```
`LBFileUploadSuccessBlock` callback doesn't have any argument but I was passing one...

**Comment by lennartstolz** [comment]
@hideya would be awesome if you'll send me a short message with your first impression of this _bugfix_. And if it's a valid fix, if you can add it to your PR or if I should create another one. But my last one is still not reviewed. So I think it would be more intelligent, if you add it to yours.

**Comment by lennartstolz** [comment]
@hideya it works! :+1: Thank you!

**Comment by hideya** [comment]
@lennartstolz thank you for checking it this quickly!  I'll update the PR to include this change!

**Comment by lennartstolz** [comment]
Sounds great! Should I close this issue? Or should it be open as long as the PR is not reviewed?

**Comment by hideya** [comment]
If the issue is resolved on your side, please feel free to close this issue :-)
Thank you again @lennartstolz for your help to fix the bug in the PR!

**Comment by lennartstolz** [comment]
Closed and bugfixes are embedded in :https://github.com/strongloop/loopback-sdk-ios/issues/54
