### ISSUE TITLE
Missing MobileCoreServices - LBFile 

### ISSUE THREAD

**Issue by soltrinox** [strongloop/loopback-sdk-ios#61]
`#import <MobileCoreServices/MobileCoreServices.h>`

missing in the LBFile.m 

Added the import and works fine now?
Maybe you want to submit change request ?

**Comment by hideya** [comment]
Would you check the version you are looking at?  The latest LBFile.m in master has the import:
https://github.com/strongloop/loopback-sdk-ios/blob/master/LoopBack/LBFile.m#L8-L10

**Comment by soltrinox** [comment]
Yes did a check... i pulling the latest from git in my Podfile  ?

pod 'LoopBack', :git => 'https://github.com/hideya/loopback-sdk-ios'
