### ISSUE TITLE
Enable unit test execution from `npm test`

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-sdk-ios#78]
Add necessary infrastructure so that `npm test` builds the framework and runs unit-tests on an emulator. See https://github.com/strongloop/loopback-sdk-ios-codegen/pull/7

**Comment by hideya** [comment]
I made a PR for this: https://github.com/strongloop/loopback-sdk-ios/pull/79  
I'm asking @rmg to integrate it into the automated checks on the CI.

**Comment by hideya** [comment]
Closing as fixed by PR #79
