### ISSUE TITLE
LB Container issue, Cannot call RestAPI methods

### ISSUE THREAD

**Issue by bhushpar82** [strongloop/loopback-sdk-ios#84]
Hi, We have implemented loopback and created a container. However we have named it as: imagecontainer in server. However when I am trying to call container related methods, I am getting error information. In this error I still see loopback api still pointing to "container" and not "imagecontainer". Not sure if this is hardcoded in SDK? Can you pls. check and let us know the issue. 

Below is the error from .getContainerWithName, this method works when we rename the model-> container (instead of imagecontainer)

Error Domain=AFNetworkingErrorDomain Code=-1011 "Expected status code in (200-299), got 404" UserInfo={NSLocalizedRecoverySuggestion={"error":{"name":"Error","status":404,"message":"There is no method to handle GET /containers/:container/files/container1?name=container1","statusCode":404,"stack":"Error: There is no method to handle GET /containers/:container/files/container1?name=container1\n    at restUrlNotFound (/usr/share/strongloop/Originale/node_modules/loopback/node_modules/strong-remoting/lib/rest-adapter.js:337:17)\n    at Layer.handle [as handle_request] (/usr/share/strongloop/Originale/node_modules/loopback/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/usr/share/strongloop/Originale/node_modules/loopback/node_modules/express/lib/router/index.js:312:13)\n    at /usr/share/strongloop/Originale/node_modules/loopback/node_modules/express/lib/router/index.js:280:7\n    at Function.process_params (/usr/share/strongloop/Originale/node_modules/loopback/node_modules/express/lib/router/index.js:330:12)\n    at next (/usr/share/strongloop/Originale/node_modules/loopback/node_modules/express/lib/router/index.js:271:10)\n    at jsonParser (/usr/share/strongloop/Originale/node_modules/loopback/node_modules/body-parser/lib/types/json.js:100:40)\n    at Layer.handle [as handle_request] (/usr/share/strongloop/Originale/node_modules/loopback/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/usr/share/strongloop/Originale/node_modules/loopback/node_modules/express/lib/router/index.js:312:13)\n    at /usr/share/strongloop/Originale/node_modules/loopback/node_modules/express/lib/router/index.js:280:7"}}, NSErrorFailingURLKey=htt8081/api/containers/:container/files/container1?name=container1, AFNetworkingOperationFailingURLRequestErrorKey=<NSMutableURLRequest: 0x7ffdf040c7f0> { URL: htt8081/api/containers/:container/files/container1?name=container1 }, AFNetworkingOperationFailingURLResponseErrorKey=<NSHTTPURLResponse: 0x7ffdf0587f00> { URL: http8081/api/containers/:container/files/container1?name=container1 } { status code: 404, headers {
    "Access-Control-Allow-Credentials" = true;
    Connection = "keep-alive";
    "Content-Encoding" = gzip;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Wed, 16 Dec 2015 21:40:15 GMT";
    Etag = "W/\"5f9-FV5GYUPBR8ppq0KW8eZKIA\"";
    "Transfer-Encoding" = Identity;
    Vary = "Origin, Accept-Encoding";
    "X-Powered-By" = Express;
} }, NSLocalizedDescription=Expected status code in (200-299), got 404}

**Comment by hideya** [comment]
According to [Storage component REST API](https://docs.strongloop.com/display/public/LB/Storage+component+REST+API) document, `[restApiRoot]/container`part is fixed.  I'm not sure but it sounds like you are trying to change the `/container` part to `/imagecontainer`?  Would you tell me how you created imagecontainer on the server side, and how you are trying to invoke it on the client side?  Exact code snippet would be helpful...

**Comment by bhushpar82** [comment]
Hi Hideya,

We plan to create separate [restApiRoot]/"xxxxxxxx" as it provides us flexibility to manage and store file(video/img/rawfiles-> analysis) by types. We have created "imagemodel" by creating a model in loopback server end and trying to push images by creating containers in it. 

 However, I am doing this not through Loopback iOS SDK. I am using RestAPIs to create containers in "imagemodel" and POST method to upload image.

so my structure is api/Imagemodel/newlycreatedcontainer/(upload or download)
(with backend creation of model)

It would be helpful, if you could configure this in iOS SDK apis where we can pass fixed api"/container" as parameter. Which allows me to use different models created on server as per the requirements

(previously I was trying to through loopback sdk methods for which I have posted the error message above). Do let me know if you need anything


Best,
Bhushan

**Comment by dexterac** [comment]
Hi Hideya,

Here is the server configuration used for the solution described by Bhushan (bhushpar82)

Server Side configuration used for the above solution:


<h3>server/datasources.json </h3>
```
  "Imagelocation": {

    "name": "Imagelocation",

    "connector": "loopback-component-storage",

    "provider": "filesystem",

    "root": "/Imagefolder"

  }
```

<h3> server/models/imagemodel.js  </h3>
```
module.exports = function(Imagemodel) {

};
```


<h3> server/models/imagemodel.json </h3>
```
{

  "name": "Imagemodel",

  "base": "Model",

  "properties": {},

  "validations": [],

  "relations": {},

  "acls": [],

  "methods": []

}
```


<h3> server/model-config.json </h3>
```
  "Imagemodel": {

    "dataSource": "Imagelocation",

    "public": true

  }
```

Now the api url is <h3>http://hostname:port/api/imagemodels/\<containers\>/\<upload | download\></h3>

**Comment by hideya** [comment]
Hi Bhushan and Atul 

Thanks for the explanations and the info.  In that case, I think you need to define your own model which is compatible with your settings (because you are not using [the standard Storage component REST API](https://docs.strongloop.com/display/public/LB/Storage+component+REST+API)).

How about simply doing something like the following?
```objc
@interface XXImageFile: LBFile
@end

@interface XXImageFileRepositoty: LBFileRepository
@end
```
```objc
@implementation XXImageFile
@end

@implementation XXImageFileRepositoty
+ (instancetype)repository {
    XXImageFileRepositoty *repository = [self repositoryWithClassName:@"imagemodels"];
    return repository;
}
@end
```
```objc
    LBRESTAdapter *adapter = [LBRESTAdapter adapterWithURL:[NSURL URLWithString:@"http://hostname:port/api"]];
    XXImageFileRepositoty *repo = (XXImageFileRepositoty*)[adapter repositoryWithClass:[XXImageFileRepositoty class]];

    [repo getFileWithName:fileName
                localPath:tmpDir
                container:container
                  success:^(LBFile *file) {
    ...
```
Hope this helps.  If you are using Swift, you might encounter some difficulties in defining `XXImageFileRepositoty`.  Please let me know in that case.

**Comment by bhushpar82** [comment]
Hi,

Indeed this worked!
Thanks for the help, now we can move to our next step of integrating socket.io 

Best,
Bhushan

**Comment by hideya** [comment]
I'm glad to know it worked!  I'll close this issue then.  Good luck!
